# Generated by Django 4.0.4 on 2022-04-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_category_name_category_brand_category_mileage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('year', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
                ('transmission', models.CharField(default='', max_length=255)),
                ('mileage', models.IntegerField(default='')),
                ('fuelType', models.CharField(default='', max_length=255)),
                ('mpg', models.FloatField(default='')),
                ('engineSize', models.FloatField(default='')),
            ],
        ),
    ]
